export const LABELS_AVAILABLE = 'LABELS_AVAILABLE';
export const CONFIRM_PRICE = 'CONFIRM_PRICE';
export const CONFIRM_ADDRESS = 'CONFIRM_ADDRESS';
export const READY = 'READY';
export const SUCCESS_COMMITMENT = 'SUCCESS_COMMITMENT';
export const SUCCES_REGISTER = 'SUCCES_REGISTER';